service: task-app-nestjs

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  memorySize: 512
  environment:
    NODE_ENV: ${opt:stage, 'dev'}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
  #dotenv:
  #  path: .env.${opt:stage, 'dev'}

package:
  individually: false
  patterns:
    - '!src/**'
    - '!test/**'
    - '!coverage/**'
    - '!*.md'
    - '!.git/**'
    - 'dist/**'
    - 'node_modules/**'